services:
  postgres:
    container_name: tutor-ms-postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin:2
    container_name: tutor-ms-zipkin
    ports:
      - "${ZIPKIN_PORT}:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    container_name: tutor-ms-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    networks:
      - spring
  eureka-server:
    image: sandangt/eureka-server:latest
    container_name: tutor-ms-eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
  apigw:
    image: sandangt/apigw:latest
    container_name: tutor-ms-apigw
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
  customer:
    image: sandangt/customer:latest
    container_name: tutor-ms-customer
    ports:
      - "${CUSTOMER_PORT}:${CUSTOMER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
  fraud:
    image: sandangt/fraud:latest
    container_name: tutor-ms-fraud
    ports:
      - "${FRAUD_PORT}:${FRAUD_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
  notification:
    image: sandangt/notification:latest
    container_name: tutor-ms-notification
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
networks:
  postgres:
  spring:

volumes:
  postgres-data:
