spring:
  application:
    name: gateway-api
  zipkin:
    baseUrl: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
server:
  port: ${API_GATEWAY_PORT}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true
