server:
  port: ${EUREKA_SERVER_PORT}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
spring:
  application:
    name: eureka-server
  zipkin:
    baseUrl: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}
